apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost-demo
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ghost
    repoURL: 'https://github.com/santoshpatil81/argocd-testing'
    targetRevision: HEAD
  project: test-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
