apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-demo
    repoURL: 'https://github.com/santoshpatil81/argocd-testing'
    targetRevision: HEAD
  project: test-project
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - preserveResourcesOnDeletion=true
    retry:
      limit: 1
      backoff:
        factor: 1
