apiVersion: batch/v1
kind: Job
metadata:
  generateName: astra-manage-app-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      volumes:
        - name: astra-control-config
          secret:
            secretName: astra-control-config
      containers:
      - name: alpine-actoolkit
        image: alpine:latest
        env:
          - name: APPNAME
            value: "ghost-argocd"
          - name: NAMESPACE
            value: "ghost"
          - name: LABEL
            value: "volume=persistent"
          - name: CLUSTERNAME
            value: "aks-eastus-cluster"
          - name: ACTOOLKIT_VERSION
            value: "2.6.2"
        command: ["/bin/sh"]
        args:
        - -c
        - >
          ls -la
        volumeMounts:
          - mountPath: /etc/astra-toolkits
            name: astra-control-config
            readOnly: true
      restartPolicy: Never
  backoffLimit: 1
