apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-sync-demo-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: alpine-post-sync
        image: alpine:latest
        command: ["/bin/sh"]
        args:
        - -c
        - >
          ls -la
      restartPolicy: Never
  backoffLimit: 1
