apiVersion: batch/v1
kind: Job
metadata:
  generateName: conftest-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      volumes:
        - name: conftest-code
          emptyDir: {}
        - name: git-secret
          secret:
            secretName: git-creds
            defaultMode: 0400
      initContainers:
        - image: registry.k8s.io/git-sync/git-sync:v4.0.0
          name: git-sync-sidecar
          args:
            - --repo=https://github.com/open-policy-agent/conftest.git
            - --depth=1
            - --period=60
            - --link=current
            - --root=/conftest-code/repo
          volumeMounts:
            - name: conftest-code
              mountPath: /conftest-code
              readOnly: false
            - name: git-secret
              mountPath: /etc/git-secret
              readOnly: true
          securityContext:
            runAsUser: 0
      containers:
        - name: conftest
          image: alpine:latest
          command: ["/bin/sh"]
          args:
          - -c
          - >
            wget 'https://github.com/open-policy-agent/conftest/releases/download/v0.42.1/conftest_0.42.1_Linux_x86_64.tar.gz' &&
            mkdir -p /tmp/conftest &&
            tar xzf conftest_0.42.1_Linux_x86_64.tar.gz --directory /tmp/conftest &&
            echo "+++++++++++++++++++" &&
            ls -lah /tmp/conftest &&
            echo "+++++++++++++++++++" &&
            ls -lah /conftest-code &&
            echo "+++++++++++++++++++" &&
            ls -lahr /conftest-code/repo &&
            echo "+++++++++++++++++++" &&
            ls -lahr /tmp/data &&
            /tmp/conftest/conftest test '/conftest-code/repo/examples/kubernetes/deployment.yaml' -p /conftest-code/repo/examples/kubernetes/policy -o json >> /tmp/out.json &&
            cat /tmp/out.json
          volumeMounts:
            - name: conftest-code
              mountPath: /conftest-code
              readOnly: true
      restartPolicy: Never
  backoffLimit: 1
