apiVersion: batch/v1
kind: Job
metadata:
  generateName: conftest-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      volumes:
        - name: conftest-code
          emptyDir: {}
      initContainers:
        - image: k8s.gcr.io/git-sync:v3.1.6
          name: git-sync-sidecar
          args:
            - "-repo=git@github.com:open-policy-agent/conftest.git"
            - "-branch=master"
            - "-depth=1"
            - "-max-sync-failures=-1"
            - "-root=/conftest"
            - "-dest=from-github"
            - "-wait=60"
            - "-ssh=true"
          volumeMounts:
            - name: conftest-code
              mountPath: /conftest-code
              readOnly: false
          securityContext:
            runAsUser: 65533
      containers:
        - name: conftest
          image: alpine:latest
          command: ["/bin/sh"]
          args:
          - -c
          - >
            wget 'https://github.com/open-policy-agent/conftest/releases/download/v0.42.1/conftest_0.42.1_Linux_x86_64.tar.gz' &&
            mkdir -p /tmp/conftest &&
            tar xzf conftest_0.42.1_Linux_x86_64.tar.gz --directory /tmp/conftest &&
            ls -lah &&
            /tmp/conftest/conftest test '/conftest-code/examples/kubernetes/deployment.yaml' -p /conftest-code/examples/kubernetes/policy -o json >> /tmp/out.json &&
            cat /tmp/out.json
          volumeMounts:
            - name: conftest-code
              mountPath: /conftest-code
              readOnly: true
      restartPolicy: Never
  backoffLimit: 1
