---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitsync-exechook-script
data:
  gitsync_exechook_cmd_to_use.sh: |
    #!/bin/sh
    # this script will be executed in active path ${GIT_SYNC_ROOT}/(hash)
    # assuming it can write and erase path /dags_dest
    # unless v level of git-sync is set to 6, echo message will not be shown in docker console.
    # Empty the /dags_dest directory
    if [ "$(ls -A /dags_dest)" ]; then
        echo "/dags_dest is not empty. Removing all files and directories."
        rm -rf /dags_dest/*
    fi
    # Copy everything under the active directory to /dags_dest
    cp -R . /dags_dest/
    echo "Files copied to /dags_dest."
    cp -R . /conftest-bin
    echo "Files copied to /conftest-bin."

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: pre-sync-conftest-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      volumes:
        - name: conftest-bin
          emptyDir: {}
        - name: oras-bin
          emptyDir: {}
        - name: policies
          emptyDir: {}
        - name: cloned-repo
          emptyDir: {}
        - name: git-secret
          secret:
            secretName: git-creds
            defaultMode: 0400
        - name: gitsync-exechook-script
          configMap:
            name: gitsync-exechook-script
            defaultMode: 0777
      initContainers:
        - image: registry.k8s.io/git-sync/git-sync:v3.6.5
          name: git-clone-repo-to-test
          args:
            - "-repo=https://github.com/open-policy-agent/conftest.git"
            - "-branch=master"
            - "-depth=1"
            - "-max-sync-failures=1"
            - "-root=/tmp/gitdata"
            - "-dest=/dags_dest/dest"
            - "-wait=60"
            - "-v=5"
            - "-one-time"
            - "-exechook-command=/tmp/gitsync_exechook_cmd_to_use.sh"
          volumeMounts:
            - name: cloned-repo
              mountPath: /dags_dest
              readOnly: false
            - name: git-secret
              mountPath: /etc/git-secret
              readOnly: true
            - name: gitsync-exechook-script
              mountPath: /tmp/gitsync_exechook_cmd_to_use.sh
              subPath: gitsync_exechook_cmd_to_use.sh
          securityContext:
            runAsUser: 65534
        - name: download-conftest
          image: alpine:latest
          command: ["/bin/sh"]
          args:
          - -c
          - >
            wget 'https://github.com/open-policy-agent/conftest/releases/download/v0.42.1/conftest_0.42.1_Linux_x86_64.tar.gz' &&
            mkdir -p /tmp/conftest &&
            tar xzf conftest_0.42.1_Linux_x86_64.tar.gz --directory /tmp/conftest &&
            mkdir -p /conftest/bin &&
            cp /tmp/conftest/conftest /conftest/bin
          volumeMounts:
            - name: conftest-bin
              mountPath: /conftest/bin
              readOnly: false
        - name: download-oras
          image: alpine:latest
          command: ["/bin/sh"]
          args:
          - -c
          - >
            wget 'https://github.com/oras-project/oras/releases/download/v1.0.0/oras_1.0.0_linux_amd64.tar.gz' &&
            mkdir -p oras-install/ &&
            tar -zxf oras_1.0.0_*.tar.gz -C oras-install/ &&
            mv oras-install/oras /oras/bin/ &&
            rm -rf oras_1.0.0_*.tar.gz oras-install/
          volumeMounts:
            - name: oras-bin
              mountPath: /oras/bin
              readOnly: false
        - name: download-policies
          image: alpine:latest
          command: ["/bin/sh"]
          args:
          - -c
          - >
            /oras/bin/oras pull docker.io/santoshpatil81/policies:latest  --output /conftest-policy
          volumeMounts:
            - name: policies
              mountPath: /conftest-policy
              readOnly: false
            - name: oras-bin
              mountPath: /oras/bin
              readOnly: true
        - name: conftest-verify
          image: alpine:latest
          command: ["/bin/sh"]
          args:
          - -c
          - >
            /conftest/bin/conftest verify -p /conftest-policy/policies
          volumeMounts:
            - name: conftest-bin
              mountPath: /conftest/bin
              readOnly: true
            - name: policies
              mountPath: /conftest-policy
              readOnly: true
      containers:
        - name: conftest
          image: alpine:latest
          command: ["/bin/sh"]
          args:
          - -c
          - >
            /conftest/bin/conftest test /git-repo/examples/kubernetes/deployment.yaml -p /conftest-policy/policies --all-namespaces
          volumeMounts:
            - name: conftest-bin
              mountPath: /conftest/bin
              readOnly: true
            - name: policies
              mountPath: /conftest-policy
              readOnly: true
            - name: cloned-repo
              mountPath: /git-repo
              readOnly: true
      restartPolicy: Never
  backoffLimit: 1
